import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { LocationProvider } from "./context/LocationContext";
import { CategoryProvider } from "./context/CategoryContext";
import { icons, Sliders } from "lucide-react";

const outfit = Outfit({
  variable: "--font-Outfit",
  subsets: ["latin"],
});



export const metadata = {
  title: "Baskit",
  icons: "logo.png",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={outfit.variable}
      >
        <LocationProvider>
        <CategoryProvider>
        <Header/>
        {children}
        </CategoryProvider>
        </LocationProvider>
      </body>
    </html>
  );
}
